//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManager.App.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessManager.App.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessManager.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ContentGridPageTitle {
            get {
                return ResourceManager.GetString("ContentGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowniki.
        /// </summary>
        public static string DictionariesGridPageTitle {
            get {
                return ResourceManager.GetString("DictionariesGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string ListDetailsListDescription {
            get {
                return ResourceManager.GetString("ListDetailsListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string ListDetailsPageTitle {
            get {
                return ResourceManager.GetString("ListDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessUserWorkflow.
        /// </summary>
        public static string ProcessUserWorkflowPageTitle {
            get {
                return ResourceManager.GetString("ProcessUserWorkflowPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ShellContentGridPage {
            get {
                return ResourceManager.GetString("ShellContentGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy.
        /// </summary>
        public static string ShellDataGridPage {
            get {
                return ResourceManager.GetString("ShellDataGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowniki.
        /// </summary>
        public static string ShellDictionariesGridPage {
            get {
                return ResourceManager.GetString("ShellDictionariesGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string ShellListDetailsPage {
            get {
                return ResourceManager.GetString("ShellListDetailsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessUserWorkflow.
        /// </summary>
        public static string ShellProcessUserWorkflowPage {
            get {
                return ResourceManager.GetString("ShellProcessUserWorkflowPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupy użytkowników.
        /// </summary>
        public static string ShellUserGroupsPage {
            get {
                return ResourceManager.GetString("ShellUserGroupsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsersInGroup.
        /// </summary>
        public static string ShellUsersInGroupPage {
            get {
                return ResourceManager.GetString("ShellUsersInGroupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne przepływy.
        /// </summary>
        public static string ShellUserWorkflowCreatePage {
            get {
                return ResourceManager.GetString("ShellUserWorkflowCreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończone przepływy.
        /// </summary>
        public static string ShellUserWorkflowsArchiveDataGridPage {
            get {
                return ResourceManager.GetString("ShellUserWorkflowsArchiveDataGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepływy do obsłużenia.
        /// </summary>
        public static string ShellUserWorkflowsDataGridPage {
            get {
                return ResourceManager.GetString("ShellUserWorkflowsDataGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja przepływu.
        /// </summary>
        public static string ShellWorkflowEditViewPage {
            get {
                return ResourceManager.GetString("ShellWorkflowEditViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepływy.
        /// </summary>
        public static string ShellWorkflowsDataGridPage {
            get {
                return ResourceManager.GetString("ShellWorkflowsDataGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroups.
        /// </summary>
        public static string UserGroupsPageTitle {
            get {
                return ResourceManager.GetString("UserGroupsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy.
        /// </summary>
        public static string UsersDataGridPageTitle {
            get {
                return ResourceManager.GetString("UsersDataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsersInGroup.
        /// </summary>
        public static string UsersInGroupPageTitle {
            get {
                return ResourceManager.GetString("UsersInGroupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserWorkflowCreate.
        /// </summary>
        public static string UserWorkflowCreatePageTitle {
            get {
                return ResourceManager.GetString("UserWorkflowCreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończone przepływy.
        /// </summary>
        public static string UserWorkflowsArchiveDataGridPageTitle {
            get {
                return ResourceManager.GetString("UserWorkflowsArchiveDataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepływy do obsłużenia.
        /// </summary>
        public static string UserWorkflowsDataGridPageTitle {
            get {
                return ResourceManager.GetString("UserWorkflowsDataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja przepływu.
        /// </summary>
        public static string WorkflowEditViewPageTitle {
            get {
                return ResourceManager.GetString("WorkflowEditViewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepływy.
        /// </summary>
        public static string WorkflowsDataGridPageTitle {
            get {
                return ResourceManager.GetString("WorkflowsDataGridPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserWorkflowArchiveDetails.
        /// </summary>
        public static string UserWorkflowArchiveDetailsPageTitle
        {
            get
            {
                return ResourceManager.GetString("UserWorkflowArchiveDetailsPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserWorkflowArchiveDetails.
        /// </summary>
        public static string ShellUserWorkflowArchiveDetailsPage
        {
            get
            {
                return ResourceManager.GetString("ShellUserWorkflowArchiveDetailsPage", resourceCulture);
            }
        }
    }
}
